version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      # Limit build resources
      args:
        BUILDKIT_STEP_LOG_MAX_SIZE: 10485760
    container_name: genie-backend
    ports:
      - "8000:8000"
    environment:
      - JULIA_NUM_THREADS=2
      - GENIE_ENV=prod
    # Runtime resource limits
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vite-frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
    # Runtime resource limits
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 512M
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge